/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

import modelo.Cliente;
import modelo.Cotizacion;
import modelo.Vehiculo;
import modelo.Venta;
import servicio.ArregloCotizaciones;
import servicio.ArregloVentas;
import servicio.DatosCompartidos;

public class FrmVendedorVentas extends javax.swing.JFrame {

    private ArregloCotizaciones servicioCotizaciones;
    private ArregloVentas servicioVentas;

    private String vendedorActual = "vendedor01";
    

    public FrmVendedorVentas() {
        initComponents();
        setLocationRelativeTo(null);

        servicioCotizaciones = DatosCompartidos.ARREGLO_COTIZACIONES;
        servicioVentas       = DatosCompartidos.ARREGLO_VENTAS;

        configurarTablas();
        actualizarTablas();
    }

    private void configurarTablas() {

        String[] cabCoti = { "N° Coti", "DNI Cliente", "Vehículo", "Total" };
        tbCotizaciones.setModel(new DefaultTableModel(null, cabCoti));


        String[] cabVentas = {
            "N° Cotización", "DNI Cliente", "Vehículo",
            "Total a pagar", "Vendedor", "Tipo facturación", "Fecha y hora"
        };
        tbVentas.setModel(new DefaultTableModel(null, cabVentas));
    }

    private void actualizarTablas() {
        actualizarTablaCotizaciones();
        actualizarTablaVentas();
    }

    private void actualizarTablaCotizaciones() {
        DefaultTableModel modelo = (DefaultTableModel) tbCotizaciones.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < servicioCotizaciones.getContador(); i++) {
            Cotizacion c = servicioCotizaciones.getCotizacion(i);

            Cliente cli = c.getCliente();
            Vehiculo v  = c.getVehiculo();

            String dniCli  = cli.getDni();
            String descVeh = v.getCodigo() + " - " + v.getMarca() + " " + v.getModelo();
            double total   = c.getPrecioFinal();   

            Object[] fila = {
                c.getNumero(),  
                dniCli,
                descVeh,
                total
            };
            modelo.addRow(fila);
        }
    }

    private void actualizarTablaVentas() {
        DefaultTableModel modelo = (DefaultTableModel) tbVentas.getModel();
        modelo.setRowCount(0);

        Venta[] arr = servicioVentas.getVentas();

        for (int i = 0; i < servicioVentas.getContador(); i++) {
            Venta vta = arr[i];
            Cotizacion c = vta.getCotizacion();
            Cliente cli  = c.getCliente();
            Vehiculo veh = c.getVehiculo();

            String dniCli  = cli.getDni();
            String descVeh = veh.getCodigo() + " - " + veh.getMarca() + " " + veh.getModelo();

            Object[] fila = {
                vta.getNumeroVenta(),      
                dniCli,
                descVeh,
                vta.getTotal(),
                vta.getVendedor(),
                vta.getTipoFacturacion(),
                vta.getFecha()
            };
            modelo.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCotizaciones = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        txtNumeroCotizacion = new javax.swing.JTextField();
        lblTitulo3 = new javax.swing.JLabel();
        txtTipoFacturacion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVentas = new javax.swing.JTable();
        lblTitulo4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbCotizaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCotizaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCotizacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCotizaciones);

        lblTitulo.setText("Cotizaciones:");

        lblTitulo1.setText("Registrear Venta");

        lblTitulo2.setText("Numero de Cotizacion");

        txtNumeroCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCotizacionActionPerformed(evt);
            }
        });

        lblTitulo3.setText("Tipo de facturacion");

        txtTipoFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoFacturacionActionPerformed(evt);
            }
        });

        tbVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbVentas);

        lblTitulo4.setText("Ventas Registradas");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo4)
                .addGap(303, 303, 303))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblTitulo1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblTitulo2)
                                .addGap(28, 28, 28)
                                .addComponent(txtNumeroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lblTitulo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTipoFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTitulo)
                                        .addGap(269, 269, 269)))))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnRegistrar)
                .addGap(165, 165, 165)
                .addComponent(btnEliminar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lblTitulo1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo2)
                    .addComponent(txtNumeroCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo3)
                    .addComponent(txtTipoFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar1)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblTitulo4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCotizacionActionPerformed

    private void txtTipoFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoFacturacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoFacturacionActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String numCoti  = txtNumeroCotizacion.getText().trim();
        String tipoFact = txtTipoFacturacion.getText().trim(); 

        if (numCoti.isEmpty() || tipoFact.isEmpty()) {
            return; 
        }

    
        Cotizacion c = servicioCotizaciones.buscarPorNumero(numCoti);
        if (c == null) {
            return; 
        }


        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String fecha = sdf.format(new Date());


        Venta vta = new Venta(
            numCoti,      
            c,
            fecha,
            tipoFact,
            vendedorActual   
        );

        servicioVentas.agregar(vta);
        actualizarTablaVentas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        String numero = txtNumeroCotizacion.getText().trim();
        if (numero.isEmpty()) {
            return;
        }

        servicioVentas.eliminarPorNumero(numero);
        actualizarTablaVentas();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FrmVendedorP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tbCotizacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCotizacionesMouseClicked
        int fila = tbCotizaciones.getSelectedRow();
        if (fila >= 0) {
            String numero = tbCotizaciones.getValueAt(fila, 0).toString(); 
            txtNumeroCotizacion.setText(numero);
        }
    }//GEN-LAST:event_tbCotizacionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendedorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendedorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendedorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendedorVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendedorVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JTable tbCotizaciones;
    private javax.swing.JTable tbVentas;
    private javax.swing.JTextField txtNumeroCotizacion;
    private javax.swing.JTextField txtTipoFacturacion;
    // End of variables declaration//GEN-END:variables
}
